name: diff_match_patch
version: 0.0.1
author: Neil Fraser <neil.fraser@gmail.com>
description: Diff, Match and Patch libraries for Plain Text
homepage: https://code.google.com/p/google-diff-match-patch/
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.10.0'
